#!/usr/bin/env bash
# shellcheck disable=SC2001
set -euo pipefail

tmp=$(mktemp)
trap 'rm -rf "$tmp"' EXIT

gh pr list \
  --author 'renovate[bot]' \
  --base main \
  --state all \
  --limit 1000 \
  --json title,mergedAt \
  --jq '.[]' >"$tmp"

manifests=(
  Gemfile
  package.json
  requirements.txt
  stack.yaml
)

swaps='
cmake-format:           cmakelang
google-java-format:     com.google.googlejavaformat:google-java-format
php-cs-fixer:           friendsofphp/php-cs-fixer
prettier-ruby:          prettier
sqlformat:              sqlparse
standardrb:             standard
'

ret=0
updated=()
waiting=()
missing=()
skipped=()

check_info() {
  local info=$1 dir dep override merged d m

  dir=$(dirname "$info")

  # The dependency name be be different from the restyler directory name
  read -r dep < <(awk "/^$dir: /"' {print $2}' <<< "$swaps"; echo "$dir")

  # If it's an override, skip it
  read -r override < <(yq '.overrides' "$dir"/info.yaml)

  if [[ "$override" != null ]]; then
    skipped+=("$dir is an override of $override")
    return 0
  fi

  # If we have a PR we're good
  while read -r merged; do
    if [[ "$merged" != "null" ]]; then
      d=$(date --date "$merged" +%Y-%m-%d)
      updated+=("$dir is updated by renovate ($d)")
      return 0
    fi
  done < <(jq -r 'select(.title | contains("update dependency '"$dep"' ")) | .mergedAt' < "$tmp")

  # If we have regex comments as depName or packageName, it's maintained
  if [[ -f "$dir"/Dockerfile ]]; then
    if grep -q "^# renovate: .* \(depName\|packageName\)=$dep\( \|$\)" "$dir"/Dockerfile; then
      waiting+=("$dir is configured, but not yet updated by renovate (Dockerfile)")
      return 0
    fi
  fi

  # If we're using a manifest that mentions it, it's maintained
  for m in "${manifests[@]}"; do
    if [[ -f "$dir/$m" ]]; then
      if grep -Fqw "$dep" "$dir/$m"; then
        waiting+=("$dir is configured, but not yet updated by renovate ($m -> $dep)")
        return 0
      else
        printf 'Warning: %s/%s exists, but does not reference %s\n' "$dir" "$m" "$dep" >&2
      fi
    fi
  done

  missing+=("$dir is not renovate-maintained")
  return 1
}

for info in */info.yaml; do
  if ! check_info "$info"; then
    ret=1
  fi
done

printf '\e[1m%s\e[0m: %d\n' "Skipped" "${#skipped[@]}"
for x in "${skipped[@]}"; do
  read -r dep msg <<<"$x"
  printf '  \e[1;36m·\e[0m \e[35m%s\e[0m %s\n' "$dep" "$msg"
done
echo

printf '\e[1m%s\e[0m: %d\n' "Updated" "${#updated[@]}"
for x in "${updated[@]}"; do
  read -r dep msg <<<"$x"
  printf '  \e[32m✓\e[0m \e[35m%s\e[0m %s\n' "$dep" "$msg"
done
echo

printf '\e[1m%s\e[0m: %d\n' "Waiting" "${#waiting[@]}"
for x in "${waiting[@]}"; do
  read -r dep msg <<<"$x"
  printf '  \e[1;33m⏲\e[0m \e[35m%s\e[0m %s\n' "$dep" "$msg"
done
echo

printf '\e[1m%s\e[0m: %d\n' "Missing" "${#missing[@]}"
for x in "${missing[@]}"; do
  read -r dep msg <<<"$x"
  printf '  \e[31m✗\e[0m \e[35m%s\e[0m %s\n' "$dep" "$msg"
done
echo

exit "$ret"
