#!/usr/bin/env bash
# shellcheck disable=SC2001
set -euo pipefail

tmp=$(mktemp)
trap 'rm -rf "$tmp"' EXIT

gh pr list \
  --author 'renovate[bot]' \
  --base main \
  --state all \
  --limit 100 \
  --json title \
  --jq '.[] | .title' | while read -r title; do
    read -r dep < <(sed 's/^feat(\(.*\)): .*$/\1/' <<<"$title")
    read -r msg < <(sed 's/^feat(.*): \(.*\)$/\1/' <<<"$title")
    grep -Fwo "$dep" <<<"$msg" || true
  done |
  sort -u >"$tmp"

ret=0
updated=0
waiting=0
missing=0

manifests=(
  Gemfile
  package.json
  requirements.txt
  stack.yaml
)

for info in */info.yaml; do
  dep=$(dirname "$info")

  read -r override < <(yq '.overrides' "$dep"/info.yaml)

  # If it's an override, skip it
  if [[ "$override" != null ]]; then
    printf ' \e[1;36m·\e[0m \e[35m%s\e[0m is an override of \e[35m%s\e[0m\n' "$dep" "$override"
    continue
  fi

  # If we have a PR we're good
  if grep -Fxq "$dep" "$tmp"; then
    ((updated++)) || true
    printf ' \e[32m✓\e[0m \e[35m%s\e[0m is updated by renovate\n' "$dep"
    continue
  fi

  # If we're using a manifest, assume it's being maintained
  for m in "${manifests[@]}"; do
    if [[ -f "$dep/$m" ]]; then
      if grep -Fqw "$dep" "$dep/$m"; then
        ((waiting++)) || true
        printf ' \e[1;33m⏲\e[0m \e[35m%s\e[0m is configured, but not yet updated by renovate (%s)\n' "$dep" "$m"
        continue 2
      fi
    fi
  done

  # If we have regex comments
  if grep -q "^# renovate: .* depName=$dep\( \|$\)" ./*/Dockerfile; then
    ((waiting++)) || true
    printf ' \e[1;33m⏲\e[0m \e[35m%s\e[0m is configured, but not yet updated by renovate\n' "$dep"
    continue
  fi

  printf ' \e[31m✗\e[0m \e[35m%s\e[0m is \e[1mnot\e[0m renovate-maintained\n' "$dep" >&2
  ((missing++)) || true
  ret=1
done

echo
printf 'Updated: \e[32m%d\e[0m, waiting: \e[33m%d\e[0m, missing: \e[31m%d\e[0m\n' "$updated" "$waiting" "$missing"
exit "$ret"
