#!/bin/sh
set -eu

usage() {
  cat <<EOM
EOM
}

job=
workflow=

while getopts j:w:h opt; do
  case "$opt" in
    j)
      job=$OPTARG
      ;;
    w)
      workflow=$OPTARG
      ;;
    h)
      usage
      exit
      ;;
    \?)
      usage >&2
      exit 64
      ;;
  esac
done

shift $((OPTIND - 1))

if [ -z "$job" ]; then
  echo "-j is required" >&2
  usage >&2
  exit 64
fi

if [ -z "$workflow" ]; then
  echo "-w is required" >&2
  usage >&2
  exit 64
fi

path=.github/workflows/$workflow.yaml
query=".jobs.$job.strategy.matrix.restyler | .[]"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

yq eval "$query" "$path" | sort >"$tmp"/matrix
wc -l "$tmp"/matrix

find . -name 'info.yaml' -printf '%h\n' | sed 's|^./||' | sort >"$tmp"/actual
wc -l "$tmp"/actual

comm -3 "$tmp"/actual "$tmp"/matrix | tee "$tmp"/diff

if [ -s "$tmp/diff" ]; then
  echo "Restylers are not correct" >&2
  exit 1
else
  echo "No differences"
fi
