ignored:
  # https://github.com/hadolint/hadolint/issues/422
  - DL3003

  # Pinning versions: more trouble than it's worth
  - DL3008 # apt-get
  - DL3018 # apk

  # Set WORKDIR before relative COPY: I want to / can do things in the default
  # workdir and I'd rather not have to look it up and re-specify it to satisfy
  # the linter.
  - DL3045

  # Multiple consecutive `RUN` instructions: We don't care to address this
  # always, only if one run is producing files cleaned up by another does it
  # actually help to make it a single execution.
  - DL3059

  # Set pipefile: I'm frequently using /bin/sh and it's not worth the noise to
  # run the stuff in an alternate shell to get this behavior.
  - DL4006

trustedRegistries:
  - docker.io
  - mcr.microsoft.com
  - quay.io
