plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "conventionalcommits"
  - - "@semantic-release/release-notes-generator"
    - preset: "conventionalcommits"
  - - "@semantic-release/github"
    - assets: "restylers.yaml"
      successCommentCondition: false
  - - "@semantic-release/git"
    - assets: "_docs"
      message: "chore(release): update docs"

branches:
  - main
  - name: rc/*
    prerelease: '${name.replace(/^rc\//g, "rc-")}'
