# yamllint disable-line rule:line-length
remote_files:
  - url: https://raw.githubusercontent.com/pbrisbin/dotfiles/master/config/brittany/config.yaml
    path: brittany.yaml
  - url: https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml
    path: .hlint.yaml
  - url: https://raw.githubusercontent.com/pbrisbin/dotfiles/master/stylish-haskell.yaml
    path: .stylish-haskell.yaml

restylers:
  - astyle
  - autopep8
  - black
  - brittany
  - clang-format
  - dfmt
  - elm-format
  - google-java-format
  #- hindent
  - hlint
  - isort
  - jdt
  #- jq
  #- ormolu
  - pg_format
  - php-cs-fixer
  - prettier
  - prettier-markdown
  #- prettier-ruby
  - prettier-yaml
  - reorder-python-imports
  - rubocop
  - rustfmt
  - shellharden
  - shfmt
  - stylish-haskell
  - terraform
  - yapf
