name: restylers
version: 0.0.0.0
license: MIT

dependencies:
  - base
  - rio

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  # Force using a pragma for this, because otherwise apply-fact barfs
  # - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: src
  dependencies:
    - Diff
    - aeson
    - errors
    - hspec
    - http-conduit
    - http-types
    - lens
    - optparse-applicative
    - semigroups
    - yaml

executables:
  restylers:
    main: Main.hs
    source-dirs: app
    dependencies:
      - restylers

tests:
  doctest:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - doctest
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - aeson
      - hspec
      - restylers
