name: whitespace
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - bytestring

executables:
  whitespace:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - optparse-applicative
      - whitespace

tests:
  whitespace-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - whitespace
