name: restylers
version: 0.0.0.0
license: AGPL-3

language: GHC2021

ghc-options:
  - -fwrite-ide-info
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missed-specialisations
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-local-signatures
  - -Wno-missing-role-annotations
  - -Wno-missing-safe-haskell-mode
  - -Wno-monomorphism-restriction
  - -Wno-prepositive-qualified-module
  - -Wno-safe
  - -Wno-unsafe
  - -optP-Wno-nonportable-include-path # https://github.com/haskell/cabal/issues/4739

dependencies:
  - base

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - GADTs
  - LambdaCase
  - NamedFieldPuns
  - NoFieldSelectors
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedRecordDot
  - OverloadedStrings
  - TypeFamilies

library:
  source-dirs: src
  dependencies:
    - Blammo
    - aeson
    - bytestring
    - errors
    - filepath
    - hspec
    - microlens
    - mtl
    - optparse-applicative
    - semigroups
    - semver
    - shakespeare
    - shellwords
    - text
    - typed-process
    - unliftio
    - yaml

executables:
  restylers:
    main: Main.hs
    source-dirs: app
    dependencies:
      - filepath
      - restylers
      - unliftio

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - filepath
      - hspec
      - restylers
      - text
      - unliftio
