#!/bin/sh
/app/node_modules/.bin/npm-groovy-lint "$@"
ret=$?

case $ret in
  1)
    # This tool lacks a --no-exit-code type of option, and it exits 1 when it
    # has found/fixed issues. So we'll exit 0 on that case.
    exit 0
    ;;
  *)
    # Any other code will be respected, because there is a few that have meaning
    # (e.g. 9 for out of memory)
    exit $ret
    ;;
esac
