#!/bin/sh
set -eu

# renovate-bot will keep the dependency as listed in build.gradle up to date,
# but we just need the executable, so we'll "parse" the version from that file
# and download it directly.
version=$(sed '/^ *compile '"'\([^']*\)'"' *$/!d; s//\1/' "$1" | awk -F: '{ print $3 }')
url="https://repo.maven.apache.org/maven2/com/google/googlejavaformat/google-java-format/1.10.0/google-java-format-$version-all-deps.jar"
jar=google-java-format.jar

curl --silent --fail --show-error --location --output "$jar" "$url"

mkdir -p ./bin
cat >./bin/google-java-format <<EOM
#!/bin/sh
exec java \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
  -jar "$PWD/$jar" "\$@"
EOM

chmod +x ./bin/google-java-format
