name: Verify other workflows

on: push

jobs:
  check-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workflow-name:
          - main
          - branch
        include:
          - workflow-name: main
            job-name: release
          - workflow-name: branch
            job-name: build
      fail-fast: false

    steps:
      - name: Install yq
        run: |
          curl -Lo yq https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64
          chmod +x ./yq
          sudo mv ./yq /usr/bin/yq
      - uses: actions/checkout@v2
      - name: Check Matrix
        run: |
          ./.github/scripts/check-matrix \
            -j ${{ matrix.job-name }} \
            -w ${{ matrix.workflow-name }}
